version: '3.8'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
    networks:
      - backend

  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - backend


  celery_worker:
    build: ./backend
    command: celery -A celery_app worker --loglevel=info
    env_file:
      - ./.env.dev
    depends_on:
      - db    
      - redis
    volumes:
      - ./backend/:/usr/src/app/
    networks:
      - backend

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 1337:80
    depends_on:
      - web
    networks:
      - backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    command: npm run start
    volumes:
      - static_volume:/usr/src/app/.next/static
    expose:
      - 3000
    env_file:
      - ./.env.prod
    networks:
      - backend

volumes:
  postgres_data:
  static_volume:
  media_volume: