version: '3.8'

services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
    networks:
      - backend

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=backend
      - POSTGRES_PASSWORD=backend
      - POSTGRES_DB=backend_dev
    networks:
      - backend

  jupyter:
    build: ./jupyter
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=k96y%tiq26be!tqb#p
    ports:
      - "8888:8888"
    volumes:
      - ./data:/home/jovyan/data
      - ./notebooks:/home/jovyan/work
    depends_on:
      - db
    networks:
      - backend

  # frontend:
  #   build: ./frontend
  #   command: npm run dev
  #   volumes:
  #     - ./frontend:/usr/src/app
  #   ports:
  #     - 3000:3000
  #   environment:
  #     - NODE_ENV=development
  #   networks:
  #     - backend


volumes:
  postgres_data:

networks:
  backend:
    driver: bridge
